"""
Convert Ulysses-MTRAG conversations to MTRAG-compatible evaluation tasks.

Mirrors the format used by MTRAG (Katsis et al., TACL 2025):
  mtrag-human/generation_tasks/RAG.jsonl — used by run_generation_eval.py
  mtrag-human/retrieval_tasks/govt/govt_lastturn.jsonl — used by run_retrieval_eval.py

This enables reusing the MTRAG evaluation scripts (scripts/evaluation/) with
minimal modification, which is a major engineering advantage.

Output formats:
  1. generation_tasks.jsonl — for RAG quality evaluation
  2. retrieval_tasks_{strategy}.jsonl — for retrieval quality evaluation (BEIR format)
  3. qrels.tsv — relevance judgments (tab-separated for pytrec_eval)
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Optional

from mestrado.synthetic.generator import Conversation, Turn
from mestrado.data.schema import Bill


def conversation_id(conv: Conversation) -> str:
    """Stable unique ID for a conversation."""
    return conv.session_id


def task_id(conv_id: str, turn_n: int) -> str:
    """MTRAG task_id format: conv_id<::>turn_n"""
    return f"{conv_id}<::>{turn_n}"


def build_input_history(conv: Conversation, up_to_turn: int) -> list[dict]:
    """
    Build the input history for a generation task up to turn n.
    Matches MTRAG format: list of {"speaker": ..., "text": ...} dicts.
    """
    history = []
    for t in conv.turns:
        if t.n > up_to_turn:
            break
        history.append({"speaker": "user", "text": t.query})
    return history


def to_generation_tasks(
    conversations: list[Conversation],
    bills_lookup: dict[str, Bill],
    top_k_contexts: int = 5,
) -> list[dict]:
    """
    Convert conversations to generation tasks (MTRAG RAG.jsonl format).

    Each task = one user turn with full conversation history up to that turn.
    contexts = top retrieved bills for that query (filled in by retriever).

    Args:
        conversations: List of generated Conversation objects
        bills_lookup: dict mapping bill.name → Bill object
        top_k_contexts: Number of context passages per task

    Returns:
        List of task dicts in MTRAG generation task format
    """
    tasks = []

    for conv in conversations:
        conv_id = conversation_id(conv)

        for turn in conv.turns:
            tid = task_id(conv_id, turn.n)

            # Build contexts from retrieved bills with judgments
            contexts = []
            for bill_name, score in list(turn.judgments.items())[:top_k_contexts]:
                bill = bills_lookup.get(bill_name)
                if bill is None:
                    continue
                contexts.append({
                    "document_id": bill_name,
                    "source": bill.sig_tipo if hasattr(bill, "sig_tipo") else "",
                    "score": float(score),
                    "text": f"{bill.name}\n{bill.txt_ementa}" if hasattr(bill, "txt_ementa") else bill.name,
                })

            # Input: full conversation history up to this turn
            input_history = build_input_history(conv, turn.n)

            # Targets: placeholder (no gold answer for legislative queries)
            # In practice: could be generated by a reference LLM
            targets = []

            task = {
                "conversation_id": conv_id,
                "task_id": tid,
                "task_type": "rag",
                "turn": str(turn.n),
                "dataset": "Ulysses-MTRAG-synthetic-v1",
                "contexts": contexts,
                "input": input_history,
                "targets": targets,
                "Question Type": [],  # could classify with LLM
                "Multi-Turn": [_turn_type_to_mtrag(turn.type)],
                "Answerability": [turn.answer_type.upper()],
                "Collection": "ulysses-mtrag-bills-pt-br",
            }
            tasks.append(task)

    return tasks


def to_retrieval_tasks(
    conversations: list[Conversation],
    strategy: str = "lastturn",
) -> list[dict]:
    """
    Convert conversations to retrieval tasks (MTRAG BEIR/JSONL format).

    Each task = one (query, task_id) pair.
    Strategy determines how the query is built from history.

    Args:
        conversations: List of Conversation objects
        strategy: "lastturn" | "questions" | "rewrite"

    Returns:
        List of dicts with _id and text (BEIR query format)
    """
    tasks = []

    for conv in conversations:
        conv_id = conversation_id(conv)

        for turn in conv.turns:
            tid = task_id(conv_id, turn.n)

            if strategy == "lastturn":
                query_text = turn.query

            elif strategy == "questions":
                # Full history formatted as MTRAG questions format
                history_parts = [
                    f'|user|: "{t.query}"'
                    for t in conv.turns
                    if t.n <= turn.n
                ]
                query_text = " ".join(history_parts)

            elif strategy == "rewrite":
                # Use the resolved query if available in turn metadata
                query_text = getattr(turn, "resolved_query", turn.query)

            else:
                query_text = turn.query

            tasks.append({"_id": tid, "text": query_text})

    return tasks


def to_qrels(conversations: list[Conversation]) -> list[tuple[str, str, int]]:
    """
    Convert conversation judgments to qrels format for pytrec_eval.

    Returns:
        List of (query_id, doc_id, relevance_score) tuples
        relevance_score: 2=r, 1=pr, 0=i
    """
    qrels = []
    score_map = {1.0: 2, 0.5: 1, 0.0: 0}  # convert to int for pytrec_eval

    for conv in conversations:
        conv_id = conversation_id(conv)

        for turn in conv.turns:
            if not turn.judgments:
                continue
            tid = task_id(conv_id, turn.n)

            for bill_name, score in turn.judgments.items():
                rel = score_map.get(float(score), 0)
                if rel > 0:  # only include relevant items
                    qrels.append((tid, bill_name, rel))

    return qrels


def save_generation_tasks(tasks: list[dict], output_path: Path) -> None:
    """Save generation tasks as JSONL (MTRAG-compatible)."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        for task in tasks:
            f.write(json.dumps(task, ensure_ascii=False) + "\n")
    print(f"[converter] Saved {len(tasks)} generation tasks → {output_path}")


def save_retrieval_tasks(tasks: list[dict], output_path: Path) -> None:
    """Save retrieval tasks as JSONL (BEIR query format)."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        for task in tasks:
            f.write(json.dumps(task, ensure_ascii=False) + "\n")
    print(f"[converter] Saved {len(tasks)} retrieval tasks → {output_path}")


def save_qrels(qrels: list[tuple], output_path: Path) -> None:
    """Save qrels as TSV (pytrec_eval format: query_id, doc_id, score)."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("query-id\tcorpus-id\tscore\n")
        for qid, did, score in qrels:
            f.write(f"{qid}\t{did}\t{score}\n")
    print(f"[converter] Saved {len(qrels)} qrels → {output_path}")


def export_full_dataset(
    conversations: list[Conversation],
    bills: list[Bill],
    output_dir: Path,
) -> None:
    """
    Export Ulysses-MTRAG in full MTRAG-compatible format.

    Creates:
      output_dir/
        generation_tasks.jsonl
        retrieval_tasks_lastturn.jsonl
        retrieval_tasks_questions.jsonl
        qrels/dev.tsv
    """
    output_dir = Path(output_dir)
    bills_lookup = {b.name: b for b in bills}

    # Generation tasks
    gen_tasks = to_generation_tasks(conversations, bills_lookup)
    save_generation_tasks(gen_tasks, output_dir / "generation_tasks.jsonl")

    # Retrieval tasks — 3 variants
    for strategy in ["lastturn", "questions", "rewrite"]:
        ret_tasks = to_retrieval_tasks(conversations, strategy=strategy)
        save_retrieval_tasks(ret_tasks, output_dir / f"retrieval_tasks_{strategy}.jsonl")

    # Qrels
    qrels = to_qrels(conversations)
    save_qrels(qrels, output_dir / "qrels" / "dev.tsv")

    print(f"\n[converter] Full Ulysses-MTRAG dataset exported to {output_dir}")
    print(f"  Conversations: {len(conversations)}")
    print(f"  Generation tasks: {len(gen_tasks)}")
    print(f"  Qrels: {len(qrels)}")


def _turn_type_to_mtrag(turn_type: str) -> str:
    """Map our turn types to MTRAG Multi-Turn enrichment values."""
    mapping = {
        "initial": "N/A",
        "follow_up": "Follow-up",
        "clarification": "Clarification",
        "nonstandalone": "Follow-up",  # closest MTRAG equivalent
        "temporal": "Follow-up",
        "comparative": "Follow-up",
    }
    return mapping.get(turn_type, "N/A")
